### ISSUE TITLE
Handler not detecting the menu

### ISSUE THREAD

**Issue by acollierr17** [Mundayne/reaction-core#8]
So I have been trying to work out this issue for some time now. But I now am opening an issue. When creating the Reaction Menu and sending it in the channel, all goes well. However, when I start reacting, nothing happens. That's because there seems to be no menu for the handler/messageReactionAdd event to detect. This is the code in my command: https://gist.github.com/acollierr17/48d12b8380888a66bbd0d3678c175c6c

And here's a GIF of what's actually happening: https://i.imgur.com/NIRxTOC.gif

I'm stuck here. Not sure if it's just me being dumb and forgetting something or if it has to do with Reaction Core (or Reaction Menu, but I'm reporting here because it's probably more so RC).

I snooped around in the code, specifically the `/src/handler.js` file and my presumption is that it's not finding the menu in the message id:
```js
15 // Find the menu, if any exists
16 let menu = this.menus[message.id]
17 // If there's no menu, stop
18 if (!menu) return
```
I'm messing around and seeing if I can come across some sort of fix. But @Mundayne if you can get to this first and provide some feedback, I'd be grateful because I plan on using this library a lot more in my future bots!

**Comment by Mundayne** [comment]
Sorry I didn't get back to you earlier, I didn't get an email or a notification or anything for this - so sorry about that. I'm looking into it, it's possibly due to setting an owner, because as far as I can see you haven't changed anything else from the example file. Try removing that line (line 18) and see if that works, and then try putting in a constant value for the ID (for example, "234786523785"), and then your variable `owner`, just to see if it really is that.
Cheers.

**Comment by acollierr17** [comment]
Hey Mundayne. Thank you for the response! It's much appreciated, So I followed your instructions and here are my results:
- I removed line 18, but that didn't make a difference
- I changed the owner variable to a) the constant variable I have set in my config (like you see in line 8) and b) I switched it out with a string value being my actual owner ID, There I didn't have any luck either.

So I think it's safe to say that ruling out the menu owner still doesn't fix this issue.

**Comment by Mundayne** [comment]
Very interesting. I'm about to start "real" work (yay life) but I'll do some proper investigation afterwards.

**Comment by acollierr17** [comment]
Any updates on this @Mundayne?

**Comment by Mundayne** [comment]
Hmm I really suck at maintaining this but I'm gonna try more starting now (early new years resolution I suppose). Closing this now, it really belongs over on https://github.com/Mundayne/reaction-menu.
